ifeq ($(findstring 86, $(ProgramFiles)), )
	PROGFILES := C:/Program Files
else
	PROGFILES := C:/Program Files (x86)
endif

GNU_INSTALL_ROOT := D:\GNU Tools ARM Embedded\4.9 2015q1
GNU_VERSION := 4.7.3
GNU_PREFIX := arm-none-eabi

